import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles(() => ({
	root: {
		height: "100%",
		width: "98%",
		display: "flex",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		float: "right",
		backgroundColor: "rgba(0,0,0,0)",
		padding: "10px 0px 10px 26px",
	},
	calendar: {
		border: "none",
		width: "100%",
		height: "100%",
	},
	barChart: {
		width: "100%",
		height: "100%",
	},
	doughnut: {
		width: "100%",
		height: "100%",
	},
	calendarDiv: {
		backgroundColor: "#fff",
		width: "88%",
		height: "38%",
		padding: "30px",
		borderRadius: "5px",
	},
	doughnutDiv: {
		backgroundColor: "#fff",
		border: "none",
		width: "88%",
		height: "38%",
		padding: "30px",
		display: "flex",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: "5px",
	},
	barChartDiv: {
		backgroundColor: "#fff",
		width: "88%",
		height: "88%",
		padding: "30px",
		display: "flex",
		flexDirection: "column",
		justifyContent: "space-around",
		alignItems: "center",
		borderRadius: "5px",
	},
	// calendarGridItem: {
	// 	height: "50%",
	// 	backgroundColor: "#fff",
	// 	display: "flex",
	// 	flexDirection: "column",
	// 	alignItems: "center",
	// 	justifyContent: "center",
	// 	// margin: "10px",
	// },
	// doughtnutGridItem: {
	// 	height: "50%",
	// 	backgroundColor: "#fff",
	// 	display: "flex",
	// 	flexDirection: "column",
	// 	alignItems: "center",
	// 	justifyContent: "center",
	// 	// margin: "10px",
	// },
	// barChartGridItem: {
	// 	height: "100%",
	// 	backgroundColor: "#fff",
	// 	display: "flex",
	// 	flexDirection: "column",
	// 	alignItems: "center",
	// 	justifyContent: "center",
	// 	// margin: "10px",
	// },
	gridItem: {
		height: "100%",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "space-around",
		// backgroundColor: "#fff",
	},
	buttonGroup: {
		width: "100%",
	},
	button: {
		width: "33%",
	},
}));
